# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60d8f9f7671af817455084e15801244df31d36d73302aee5d281427114fa46f37128834ffe082d2a7ab90d367dc2f45f97134426d8531d3cca6af81dc2e570b0

test:
  secret_key_base: 01eaa2b5e1a271ced11ba744fa84179ea26b1991f6ebec1ddd1f2512cd3786cc017813bb8d9208e6508f1fdf96fc3f1d48a6008ce8eaa799d19a35a83a09a8a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
